### ISSUE TITLE
Exit the program when using menus under raspbian

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#158]
hi,

When i use the menus under raspbian, Orca closes suddenly. Same issue with Pilot.

maybe this message could be the reason why.
```
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
ATTENTION: default value of option force_s3tc_enable overridden by environment.
pi@pi02:~/audio/Orca/desktop $ node --version
v12.6.0
pi@pi02:~/audio/Orca/desktop $ npm --version
6.9.0
pi@pi02:~/audio/Orca/desktop $ 

```

**Comment by neauoire** [comment]
Not sure : /

**Comment by martinberlin** [comment]
I must say I'm not an experienced Raspian user to start with. But I also had problems to do an npm install in the small PC:
Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:536:15)
```
pi@raspberrypi:~/Orca/desktop $ nodejs -v
v12.6.0
pi@raspberrypi:~/Orca/desktop $ npm -v
5.5.1
```
So I decided to use the Orca-C instead of this version. But I guess there is an easy way to fix it as in my laptop works perfectly with an older version of nodejs (8.10)

**Comment by kroppian** [comment]
I'm able to reproduce the bug on 32 bit Debian 9. Getting the exact same warnings as you do as well.

**Comment by neauoire** [comment]
I think it has to do with the icon that displays on quit, does the error also happens on save?

**Comment by nlebellier** [comment]
For me it was for all menus not a specific one. may it helps.

**Comment by ChrisPhillips222** [comment]
Hi, I’ve installed Orca on an old netbook running lubuntu 18.10 and I’m getting the following error whenever I try to select anything in the menu:

Glib-GIO-CRITICAL **: (timestamp): g_dbus_proxy_new: assertion ‘G_IS_DBUS_CONNECTION (connection)’ failed

based on some things I've read after furious googling I purged fcitx-module-dbus. Now it doesn't give the error but will still exit the program if I try to use the menu.

**Comment by ryanramage** [comment]
I was having this problem, but today I updated from git, did an npm install, and now orca runs fine on the pi! No more menu crashing!

**Comment by koshimazaki** [comment]
> I was having this problem, but today I updated from git, did an npm install, and now orca runs fine on the pi! No more menu crashing!

@ryanramage are you using ORCA or orca-c ?

**Comment by koshimazaki** [comment]
I managed to get to work both ORCA and orca-c on PI4. 
ORCA needs **node.js** and **electron** installing. It needs newer one to run npm. Might be worth adding that in the installation guide. 

I also experience crashes with menus but while using key combinations to get to menu it seem to work fine. ORCA is lagging a bit once injecting files or while more operators are present on screen. No problem with saving and loading the files tho.

**Comment by neauoire** [comment]
Could someone pull the latest changes and test orca on RPi, and tell me if that works for you?

**Comment by martinberlin** [comment]
On my Raspberry 4 the electron post install hook is failing.

```
$ npm install

> electron@7.1.0 postinstall /home/pi/Programs/Orca/desktop/node_modules/electron
> node install.js

(node:1750) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/pi/Programs/Orca/desktop/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:210:5)
    at module.exports (/home/pi/Programs/Orca/desktop/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/pi/Programs/Orca/desktop/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/home/pi/Programs/Orca/desktop/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
(node:1750) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1750) 
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nlebellier** [comment]
Hi

i try today with the latest version of Orca.

```
pi@raspberrypi:~/audio/Orca/desktop $ npm install

> core-js@3.3.6 postinstall /home/pi/audio/Orca/desktop/node_modules/core-js
> node postinstall || echo "ignore"


> electron@7.1.0 postinstall /home/pi/audio/Orca/desktop/node_modules/electron
> node install.js

(node:1081) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/pi/audio/Orca/desktop/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:210:5)
    at module.exports (/home/pi/audio/Orca/desktop/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/pi/audio/Orca/desktop/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/home/pi/audio/Orca/desktop/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
(node:1081) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1081) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN Orca@0.1.0 No description
npm WARN Orca@0.1.0 No repository field.
npm WARN Orca@0.1.0 No license field.

added 165 packages from 137 contributors and audited 346 packages in 9.273s
pi@raspberrypi:~/audio/Orca/desktop $ sudo apt update
Atteint :1 https://deb.nodesource.com/node_12.x buster InRelease
Réception de :2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
Réception de :3 http://archive.raspberrypi.org/debian buster InRelease [25,2 kB] 
Réception de :4 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13,0 MB]
Réception de :5 http://archive.raspberrypi.org/debian buster/main armhf Packages [259 kB]
13,3 Mo réceptionnés en 16s (856 ko/s)                                                                                                    
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
15 paquets peuvent être mis à jour. Exécutez « apt list --upgradable » pour les voir.
pi@raspberrypi:~/audio/Orca/desktop $ npm --version
6.13.0
pi@raspberrypi:~/audio/Orca/desktop $ node --version
v12.13.0
pi@raspberrypi:~/audio/Orca/desktop $ 
```

**Comment by neauoire** [comment]
I've added a little `--gpu_disabled` command to the `start` command, maybe that will fix the menu issues?
